<a href="https://colab.research.google.com/github/shitalarote/python-assignment-/blob/main/Numpay_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Q 1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**


**Ans**

### **Purpose and Advantages of NumPy in Scientific Computing and Data Analysis**

NumPy (Numerical Python) is a fundamental package for scientific computing in Python. It provides powerful tools for working with numerical data, especially multi-dimensional arrays (ndarrays), and supports a wide range of mathematical, logical, statistical, and algebraic operations.

### **Purpose of NumPy**
**1.**Efficient Numerical Computation: Provides fast, memory-efficient array operations.

**2.**Foundation for Other Libraries: Forms the core of the scientific Python ecosystem (e.g., SciPy, Pandas, TensorFlow).

**3.**Support for Multi-Dimensional Arrays: Enables manipulation of arrays of any shape or size with ease.

## **Advantages of NumPy**

**1.Feature **

N-Dimensional Arrays

**Description**

Supports ndarray objects for efficient array storage and operations.

**2.Feature **

Speed

**Description**

Operations on arrays are implemented in C, making them significantly faster than pure Python loops.

**3.Feature **

Broadcasting

**Description**

Allows arithmetic operations between arrays of different shapes without explicit looping.


**4.Feature **

Vectorization

**Description**

Replaces explicit loops with array expressions, improving code clarity and performance.


**5.Feature **

Memory Efficiency

**Description**

Uses less memory by leveraging contiguous memory blocks and data type control.

**6.Feature **

Comprehensive Functions

**Description**

Includes functions for linear algebra, statistics, Fourier transforms, and more.

**7.Feature **

Integration

**Description**

Easily integrates with C/C++, Fortran, and other Python libraries.

## **How NumPy Enhances Python's Capabilities**

**1.Performance:** Native Python is slow for large numerical computations due to interpreted execution and lack of vectorized operations. NumPy overcomes this by leveraging optimized C-based operations.

**2.Array-Oriented Computation:** Enables operations on entire datasets (arrays/matrices) without writing loops, making code shorter and faster.

**3.Advanced Indexing and Slicing:** Provides powerful ways to manipulate subsets of data easily.

**4.Interoperability:** NumPy arrays can be easily used with other libraries like Pandas, Matplotlib, SciPy, and machine learning frameworks like Scikit-learn and TensorFlow.

**5.Mathematical Abstractions:** Provides high-level abstractions for complex mathematical operations like matrix multiplication, eigenvalue computation, and statistical analysis.


# **Q 2. Compare and contrast np.mean() and np.average() functions in NumPy.** **When would you use one over the other?**

**Ans**

Comparison of np.mean() and np.average() in NumPy
Both np.mean() and np.average() are used to compute the average value of array elements, but they differ in functionality and use cases.

## **Key Differences**



| Feature              | `np.mean()`                                              | `np.average()`                                                                        |
| -------------------- | -------------------------------------------------------- | ------------------------------------------------------------------------------------- |
| **Basic Function**   | Computes the **arithmetic mean** (sum divided by count). | Computes a **weighted average** (if weights are provided).                            |
| **Weights**          | Not supported.                                           | Supports weights for each element.                                                    |
| **Default Behavior** | Simple mean across all or specified axis.                | Simple mean if weights are `None`; otherwise, computes weighted average.              |
| **Return Type**      | Always returns a scalar or array of means.               | Returns a scalar or array, **plus optional `returned=True`** can give sum of weights. |
| **Use Case**         | When all data points are equally important.              | When data points have different importance (weights).                                 |

## **Example Usage**
**1. np.mean()**

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
mean_value = np.mean(data) # Output: 2.5

**2. np.average() without weights**

In [ ]:
average_value = np.average(data)  # Output: 2.5

**3. np.average() with weights**

In [ ]:
weights = np.array([1, 1, 1, 3])
weighted_avg = np.average(data, weights=weights)  # Output: 3.25

**4. Using returned=True with np.average()**

In [ ]:
weighted_avg, sum_weights = np.average(data, weights=weights, returned=True)
# Output: (3.25, 6.0)

## **When to Use Which**

| Scenario                                       | Recommended Function                          |
| ---------------------------------------------- | --------------------------------------------- |
| All values equally important                   | `np.mean()` or `np.average()` without weights |
| Values have different weights or significance  | `np.average()` with `weights=`                |
| Want clarity and simplicity                    | `np.mean()`                                   |
| Need to return both average and sum of weights | `np.average(..., returned=True)`              |


# **Q 3. Describe the methods for reversing a NumPy array along different** **axes. **Provide examples for 1D and 2D arrays.**

**Ans-**

### **Reversing a NumPy Array Along Different Axes**

Reversing elements in a NumPy array can be done in several ways depending on the array's dimensions and the axis you want to reverse along. Here’s how it's done:

## **Reversing a 1D Array**

### **Example:**


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]

**Explanation:**

[::-1] slices the array in reverse order (from end to start).

## **Reversing a 2D Array**
Let’s say you have:

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

### **1. Reverse the rows (axis=0):**

In [ ]:
rev_rows = arr2d[::-1, :]
print(rev_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

### **2. Reverse the columns (axis=1):**

In [ ]:
rev_cols = arr2d[:, ::-1]
print(rev_cols)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

### **3. Reverse both rows and columns:**

In [ ]:
rev_both = arr2d[::-1, ::-1]
print(rev_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

## **Alternative Method:** np.flip()

The np.flip() function provides a cleaner way to reverse along specified axes.

**1. Flip along rows (axis 0):**

In [ ]:
np.flip(arr2d, axis=0)

**2. Flip along columns (axis 1):**

In [ ]:
np.flip(arr2d, axis=1)

**3. Flip all axes:**

In [ ]:
np.flip(arr2d)  # Equivalent to reversing both axes

**Table-**

| Operation                | Slice Notation    | `np.flip()` Equivalent |
| ------------------------ | ----------------- | ---------------------- |
| Reverse 1D               | `arr[::-1]`       | `np.flip(arr)`         |
| Reverse rows (axis 0)    | `arr[::-1, :]`    | `np.flip(arr, axis=0)` |
| Reverse columns (axis 1) | `arr[:, ::-1]`    | `np.flip(arr, axis=1)` |
| Reverse both axes        | `arr[::-1, ::-1]` | `np.flip(arr)`         |


# **Q 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance**.




**Ans-**

## **Determining the Data Type of Elements in a NumPy Array**

To determine the data type of elements in a NumPy array, use the .dtype attribute.

## **Example:**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32 depending on system)

If the array contains floats or mixed types:

In [ ]:
arr2 = np.array([1.5, 2.0, 3.7])
print(arr2.dtype)  # Output: float64

## **Why Data Types Matter in NumPy**

### **1. Memory Management**

NumPy arrays are stored in contiguous blocks of memory, and the data type (dtype) determines how much memory each element uses.

| Data Type | Bytes   |
| --------- | ------- |
| `int8`    | 1 byte  |
| `int32`   | 4 bytes |
| `float64` | 8 bytes |


An array of 1,000,000 int64 integers uses ~8 MB, but using int8 reduces that to ~1 MB.

### **2. Performance**

Operations on fixed-type arrays are highly optimized at the C level, making them much faster than native Python lists.

Using the appropriate dtype ensures faster computation and lower overhead, especially in large-scale computations or machine learning workflows.

### **3. Data Integrity**

Using a consistent data type avoids unintended type conversions (which can be slow or error-prone).

### **Example:**


In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # float32

If you accidentally mix data types, NumPy will upcast (e.g., from int to float), which may use more memory or affect results.

### **4. Custom dtypes and Structured Arrays**

NumPy also supports custom and structured dtypes for more complex data handling (like database records or CSV parsing).

# **Q 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**Ans-**

### **Definition and Features of ndarray in NumPy**

 **Definition:**

In NumPy, an ndarray (short for N-dimensional array) is a powerful, multi-dimensional container for homogeneous data (all elements of the same type). It forms the core of NumPy’s array-processing capabilities.



In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(type(arr))  # Output: <class 'numpy.ndarray'>

### **Key Features of ndarray**

| Feature                     | Description                                                               |
| --------------------------- | ------------------------------------------------------------------------- |
| **Multidimensional**        | Supports 1D, 2D, 3D, and higher-dimensional arrays.                       |
| **Homogeneous**             | All elements must be of the same data type (`dtype`).                     |
| **Fixed Size**              | Once created, the array size is fixed (unlike lists, which are dynamic).  |
| **Efficient Storage**       | Stored in **contiguous memory**, enabling fast access and processing.     |
| **Broadcasting**            | Supports broadcasting for arithmetic operations across different shapes.  |
| **Vectorized Operations**   | Enables element-wise operations without explicit loops.                   |
| **Built-in Math Functions** | Supports a wide range of operations: sum, mean, dot, reshape, etc.        |
| **Shape and Dimension**     | Attributes like `.shape`, `.ndim`, and `.size` give array structure info. |


### **ndarray vs. Python List**


| Feature               | `ndarray`                                                       | Python List                                   |
| --------------------- | --------------------------------------------------------------- | --------------------------------------------- |
| **Data Type**         | Homogeneous (e.g., all `int32`)                                 | Heterogeneous (mixed types allowed)           |
| **Performance**       | Fast (C-backed, vectorized)                                     | Slow for large numerical operations           |
| **Functionality**     | Rich set of numerical functions (e.g., `.mean()`, `.reshape()`) | Limited to basic operations                   |
| **Memory Efficiency** | More efficient due to fixed-type, contiguous storage            | Less efficient (pointers to separate objects) |
| **Dimensionality**    | Supports multi-dimensional arrays                               | Nested lists are cumbersome for >1D           |
| **Broadcasting**      | Supported                                                       | Not supported                                 |
| **Looping Needed?**   | No (vectorized)                                                 | Yes (for element-wise ops)                    |


### **Example Comparison**

In [ ]:
# Python list
lst = [1, 2, 3]
# NumPy array
arr = np.array([1, 2, 3])

# Multiply each element by 2
print([x * 2 for x in lst])  # List: [2, 4, 6]
print(arr * 2)               # ndarray: [2 4 6] (vectorized)

# **Q 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**Ans-**

### **Performance Benefits of NumPy Arrays over Python Lists in Large-Scale Numerical Operations**

When handling large-scale numerical computations, NumPy arrays (ndarray) are significantly faster and more memory-efficient than Python lists. Here's why:

### **1. Vectorization (No Explicit Loops)**

**NumPy** uses **vectorized operations** (executed in optimized C code), whereas Python lists require explicit loops for element-wise operations.

### **Example:**

In [ ]:
import numpy as np
import time

# Large data size
size = 1_000_000

# NumPy array
a = np.arange(size)
start = time.time()
a = a * 2
print("NumPy time:", time.time() - start)

# Python list
b = list(range(size))
start = time.time()
b = [x * 2 for x in b]
print("List time:", time.time() - start)

### **Expected Output:**

NumPy: much faster (milliseconds)

List: significantly slower (often seconds)

### **2. Memory Efficiency**

**NumPy arrays** use a fixed data type and contiguous memory blocks → lower memory usage.

**Python lists** store pointers to individual objects → higher overhead.

### **Example:**

In [ ]:
import sys

list_data = list(range(1000))
array_data = np.array(list_data)

print("List memory:", sys.getsizeof(list_data))          # ~9000+ bytes
print("Array memory:", array_data.nbytes)               # ~4000 bytes (int32)

### **3. Built-in Optimized Functions**

NumPy provides highly optimized implementations for mathematical and statistical operations:

In [ ]:
np.mean(arr), np.sum(arr), np.dot(arr1, arr2), np.std(arr), etc.

These are much faster than manually implemented loops or list comprehensions.



### **4. Parallelization & SIMD**

NumPy operations often take advantage of SIMD (Single Instruction, Multiple Data) and multi-threaded C libraries (like BLAS, LAPACK), allowing even more speed-up.

### **5. Broadcasting Support**

NumPy can perform operations between arrays of different shapes without copying data explicitly.



In [ ]:
a = np.array([1, 2, 3])
b = 2
print(a + b)  # Output: [3 4 5]

No such functionality exists in pure Python lists without writing manual loops.

### **Table**

| Feature                 | NumPy Array              | Python List                |
| ----------------------- | ------------------------ | -------------------------- |
| Speed                   | ✅ Fast (C-optimized)     | ❌ Slow                     |
| Memory Usage            | ✅ Low (contiguous block) | ❌ High (object references) |
| Operations              | ✅ Vectorized             | ❌ Loop-based               |
| Broadcasting            | ✅ Supported              | ❌ Not supported            |
| Built-in Math Functions | ✅ Extensive              | ❌ Minimal                  |


For large-scale numerical tasks, NumPy arrays offer dramatic improvements in speed, memory use, and simplicity, making them the go-to choice for data science, machine learning, and scientific computing

# **Q 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**Ans-**
**Comparison of** np.vstack() **and** np.hstack() **in NumPy**
Both vstack() and hstack() are used to **concatenate arrays**, but along **different axes:**


np.vstack() → Vertical stack → stacks arrays row-wise (along axis=0).

np.hstack() → Horizontal stack → stacks arrays column-wise (along axis=1 for 2D arrays).


### **1D Array Example**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


np.vstack([a, b])

In [ ]:
print(np.vstack([a, b]))
# Output:
# [[1 2 3]
#  [4 5 6]]


**Shape:** (2, 3)

np.hstack([a, b])

In [ ]:
print(np.hstack([a, b]))
# Output:
# [1 2 3 4 5 6]


**Shape:** (6,) → still 1D

### **2D Array Example**

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


np.vstack([a, b])

In [ ]:
print(np.vstack([a, b]))
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]


**Adds more rows**

np.hstack([a, b])

In [ ]:
print(np.hstack([a, b]))
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


Adds more columns

### **Key Differences**

| Feature       | `np.vstack()`     | `np.hstack()`        |
| ------------- | ----------------- | -------------------- |
| Direction     | Vertical (rows)   | Horizontal (columns) |
| Axis          | `axis=0`          | `axis=1`             |
| Requires Same | Number of columns | Number of rows       |
| Adds          | New rows          | New columns          |


Use vstack() when you want to add new rows (stack arrays vertically).

Use hstack() when you want to add new columns (stack arrays horizontally).

Both are useful for building datasets, combining features, or reshaping data in data science tasks.

# **Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

**Ans-**

**Differences Between** np.fliplr() **and** np.flipud() **in NumPy**
Both np.fliplr() and np.flipud() are used to **flip (reverse)** arrays, but they operate along **different axes** and are primarily intended for **2D arrays.**

### **Function Overview**

| Function      | Meaning                | Axis Affected                                                                  | Typical Use     |
| ------------- | ---------------------- | ------------------------------------------------------------------------------ | --------------- |
| `np.fliplr()` | **Flip Left to Right** | Flips array in the **left/right direction** → operates on **columns (axis=1)** | Horizontal flip |
| `np.flipud()` | **Flip Up to Down**    | Flips array in the **up/down direction** → operates on **rows (axis=0)**       | Vertical flip   |

### **Example with a 2D Array**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


np.fliplr(arr)

In [ ]:
print(np.fliplr(arr))
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


Flips columns (horizontal mirror)

np.flipud(arr)

In [ ]:
print(np.flipud(arr))
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


Flips rows (vertical mirror)

### **Important Notes**

Both functions require at least 2D input; they raise an error with 1D arrays:

In [ ]:
np.fliplr(np.array([1, 2, 3]))  # ❌ ValueError
np.flipud(np.array([1, 2, 3]))  # ✅ Works (equivalent to arr[::-1])


They are specialized versions of the more general np.flip() function:

In [ ]:
np.flip(arr, axis=1)  # Same as np.fliplr()
np.flip(arr, axis=0)  # Same as np.flipud()


**Table**

| Feature       | `np.fliplr()`                | `np.flipud()`                |
| ------------- | ---------------------------- | ---------------------------- |
| Direction     | Left-right (horizontal flip) | Up-down (vertical flip)      |
| Axis Affected | Columns (`axis=1`)           | Rows (`axis=0`)              |
| Input Type    | Requires 2D+ arrays          | Works with 1D and 2D+ arrays |
| Common Use    | Image processing, matrix ops | Reversing row order, etc.    |


# **Q 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans-**

**Functionality of** np.array_split() **in NumPy**

The np.array_split() function is used to split an array into multiple sub-arrays, similar to np.split(), but with one key difference:

 It can handle cases where the array cannot be split evenly, distributing elements as evenly as possible.

### **Syntax:**

In [ ]:
np.array_split(array, num_splits, axis=0)


**array:** The input array.

**num_splits:** Number of parts to split into.

**axis:** The axis along which to split (default is axis=0, i.e., rows for 2D arrays).



### **Example: 1D Array (Uneven Split)**



In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6])

# Split into 3 parts
parts = np.array_split(arr, 3)
for part in parts:
    print(part)


Total elements: 7

Requested parts: 3

Split sizes: [3, 2, 2]

### **How It Handles Uneven Splits**

It calculates the base size of each split: len(arr) // num_splits

Then, it distributes the remainder (if any) across the first few splits.

**For example:**

array_split([0,1,2,3,4], 2) → sizes: [3, 2]

array_split([0,1,2,3,4], 3) → sizes: [2, 2, 1]



### **Example: 2D Array (Split along axis=1)**

In [ ]:
arr2d = np.array([[1, 2, 3, 4, 5, 6]])

# Split into 4 columns
parts = np.array_split(arr2d, 4, axis=1)
for part in parts:
    print(part)


### **Difference from np.split()**

In [ ]:
np.split(arr, 3)  # ❌ Raises ValueError if arr can't be split evenly
np.array_split(arr, 3)  # ✅ Works, even if uneven


### **Table**

| Feature                           | `np.array_split()` |
| --------------------------------- | ------------------ |
| Splits arrays into multiple parts | ✅                  |
| Handles uneven splits             | ✅                  |
| Accepts axis parameter            | ✅                  |
| Returns list of sub-arrays        | ✅                  |
| Safer than `np.split()`           | ✅                  |


# **Q 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

**Ans-**

### **Vectorization and Broadcasting in NumPy**

NumPy is designed for **high-performance numerical computing**, and two core concepts that make this possible are **vectorization** and **broadcasting.**

## **1. Vectorization**

### **What It Is:**

Vectorization refers to performing operations on entire arrays without using explicit Python loops. It leverages underlying C-level implementations for fast execution.

### K**ey Benefit:**

**Faster** than loops

**Cleaner** syntax

**More efficient memory use**

## **Example:**

In [ ]:
import numpy as np

# Traditional loop approach (slow)
a = list(range(1000000))
b = [x * 2 for x in a]

# Vectorized NumPy approach (fast)
arr = np.arange(1000000)
result = arr * 2


**Result:** NumPy’s vectorized version is ~10–100× faster.

## **2. Broadcasting**
###  **What It Is:**
Broadcasting allows arrays of different shapes to be used together in arithmetic operations without explicitly copying or reshaping data.

###  **Key Benefit:**
Saves memory and computation time

Avoids unnecessary array replication

### **Example:**


In [ ]:
a = np.array([1, 2, 3])        # Shape: (3,)
b = np.array([[10], [20], [30]])  # Shape: (3, 1)

# Broadcasting occurs here
print(a + b)


a is broadcast across columns

b is broadcast across rows



## **Broadcasting Rules Summary:**
1.If arrays have different ranks (number of dimensions), NumPy **pads the** **smaller shape with 1s** on the left.

2.Dimensions are **compatible** when:

They are equal, or

One of them is 1

3.Broadcasting expands size **only in memory view**, not physically.





## **Why These Concepts Matter**

| Benefit             | Vectorization             | Broadcasting                       |
| ------------------- | ------------------------- | ---------------------------------- |
| Performance         | ✅ Eliminates Python loops | ✅ Avoids unnecessary memory copies |
| Cleaner Syntax      | ✅                         | ✅                                  |
| Memory Efficient    | ✅                         | ✅                                  |
| Enables Complex Ops | ✅ Fast math functions     | ✅ Shape-matching arithmetic        |


## **Real-Life Use Case Example**

Adding a scalar to a matrix:

In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr + 10)  # Broadcasting: adds 10 to every element


Normalizing rows:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_sums = arr.sum(axis=1, keepdims=True)  # shape (2,1)
norm = arr / row_sums  # Broadcasting works automatically


### **Table**

| Concept           | Definition                                      | Boosts                         |
| ----------------- | ----------------------------------------------- | ------------------------------ |
| **Vectorization** | Replace loops with array-wide operations        | Speed, readability             |
| **Broadcasting**  | Implicitly expands arrays with different shapes | Flexibility, memory efficiency |


# **Practical Questions:**

# **1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

**Task: Create a 3×3 NumPy Array and Transpose It**
Here’s how you can do it using NumPy:



In [ ]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)

# Interchange rows and columns (transpose the array)
transposed_arr = arr.T
print("Transposed Array:\n", transposed_arr)


### **Explanation:**
np.random.randint(1, 101, size=(3, 3)): Generates a 3×3 array of random integers from 1 to 100 (inclusive of 1, exclusive of 101).

T: Transposes the array (swaps rows with columns).



# **2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

Here's how you can generate a 1D NumPy array and reshape it into different dimensions:





In [ ]:
import numpy as np

# Step 1: Generate a 1D array with 10 elements
arr = np.arange(10)
print("Original 1D Array:\n", arr)

# Step 2: Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", arr_2x5)

# Step 3: Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", arr_5x2)


### **Notes:**
reshape(rows, columns) requires that the total number of elements remains the same.

You can reshape in any configuration as long as the product of dimensions equals 10 in this case.

# **3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

We can create a 4x4 NumPy array with random float values and add a border of zeros using np.pad() like this:




In [ ]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:\n", arr)

# Step 2: Add a border of zeros to make it a 6x6 array
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", arr_with_border)


### **Explanation:**
np.random.rand(4, 4) → generates random floats in [0, 1).

np.pad(..., pad_width=1) → adds one layer of padding (rows and columns) on all sides.

mode='constant', constant_values=0 → specifies the border should be filled with zeros.

# **4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

We can create an array of integers from 10 to 60 with a step of 5 using np.arange():






In [ ]:
import numpy as np

arr = np.arange(10, 61, 5)
print("Array from 10 to 60 with step of 5:\n", arr)


np.arange(start, stop, step) generates values from start to stop (inclusive of start, exclusive of stop unless step fits exactly).

Since 60 is exactly reachable from 10 in steps of 5, it's included.

# **5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

We can create a NumPy array of strings and apply different case transformations using NumPy's char module, which supports vectorized string operations.

### **Example:**

In [ ]:
import numpy as np

# Create the array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
upper_arr = np.char.upper(arr)
lower_arr = np.char.lower(arr)
title_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)
swapcase_arr = np.char.swapcase(arr)

# Print results
print("Original:", arr)
print("Uppercase:", upper_arr)
print("Lowercase:", lower_arr)
print("Title Case:", title_arr)
print("Capitalized:", capitalize_arr)
print("Swap Case:", swapcase_arr)


np.char.upper() → Converts to uppercase

np.char.lower() → Converts to lowercase

np.char.title() → Capitalizes each word

np.char.capitalize() → Capitalizes only the first letter

np.char.swapcase() → Swaps case of each letter

# **6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

We can generate a NumPy array of words and insert a space between each character of every word using np.char.join().

### **Example:**


In [ ]:
import numpy as np

# Step 1: Create an array of words
words = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert space between each character in every word
spaced_words = np.char.join(' ', words)

# Step 3: Display the result
print("Original Words:", words)
print("Spaced Words:", spaced_words)


### **How It Works:**

np.char.join(' ', words) joins each character in the string with a space.

This operation is vectorized, so it's applied to every element in the array efficiently.

# **7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**



We can create two 2D NumPy arrays and perform element-wise operations like addition, subtraction, multiplication, and division as follows:

### **Example:**

In [ ]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
add_result = arr1 + arr2

# Element-wise subtraction
sub_result = arr1 - arr2

# Element-wise multiplication
mul_result = arr1 * arr2

# Element-wise division
div_result = arr1 / arr2

# Display the results
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("\nElement-wise Addition:\n", add_result)
print("\nElement-wise Subtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)
print("\nElement-wise Division:\n", div_result)


### **Explanation:**
**Addition (+):** Adds corresponding elements of both arrays.

**Subtraction (-):** Subtracts corresponding elements of the second array from the first.

**Multiplication**(*):Multiplies corresponding elements.

**Division (/):** Divides corresponding elements of the first array by the second.

These operations are performed **element-wise**, meaning the operation is applied to each corresponding pair of elements from the two arrays.

# **8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

We can create a 5x5 identity matrix using np.eye() and then extract its diagonal elements using np.diag().

### **Example:**

In [ ]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


### **Explanation:**
np.eye(5) creates a 5x5 identity matrix with ones on the diagonal and zeros elsewhere.

np.diag(identity_matrix) extracts the diagonal elements from the matrix, which are all 1s in the case of the identity matrix.

# **9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**

We can generate a NumPy array of 100 random integers between 0 and 1000, then filter out the prime numbers using a custom prime-checking function.

### **Full Example:**

In [ ]:
import numpy as np

# Step 1: Generate random integers
arr = np.random.randint(0, 1001, size=100)

# Step 2: Define a vectorized function to check for primes
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

# Vectorize the function
vectorized_is_prime = np.vectorize(is_prime)

# Step 3: Apply it to the array and filter
primes = arr[vectorized_is_prime(arr)]

# Step 4: Display
print("Original Array:\n", arr)
print("\nPrime Numbers in the Array:\n", primes)


### **How It Works:**
np.random.randint(0, 1001, size=100): generates 100 random integers between 0 and 1000.

is_prime() checks if a number is prime.

np.vectorize() allows applying the function element-wise over the array.

Array indexing arr[mask] selects only prime numbers.

# **10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

We can represent daily temperatures for a 30-day month using a 1D NumPy array and compute weekly averages by reshaping the array into weeks (assuming 4 full weeks + 2 extra days, or rounding accordingly).

### **Example (Assuming 30 Days):**



In [ ]:
import numpy as np

# Step 1: Generate daily temperatures for 30 days (e.g., random values between 15°C and 35°C)
daily_temps = np.random.uniform(15, 35, size=30)
print("Daily Temperatures:\n", daily_temps)

# Step 2: Reshape into 5 weeks of 6 days each OR 4 weeks of 7 days (we'll use 4 full weeks here)
weeks = daily_temps[:28].reshape(4, 7)  # Use first 28 days

# Step 3: Calculate weekly averages
weekly_averages = weeks.mean(axis=1)
print("\nWeekly Averages (Week 1 to Week 4):\n", weekly_averages)

# Optional: Show any remaining days
remaining_days = daily_temps[28:]
if remaining_days.size > 0:
    print("\nRemaining Days (not included in averages):\n", remaining_days)


### **Explanation:**
np.random.uniform(15, 35, size=30): Generates float values for temperatures.

.reshape(4, 7): Organizes into 4 full weeks of 7 days.

.mean(axis=1): Calculates mean temperature for each row (week).